### PR TITLE
Add method to generate receipts url

### PR DESCRIPTION
**Pull request by osanyin**
Add method to generate the correct url for each invoice receipt.

### CODE REVIEW

**Comment by dmitryrck** [comment]
@RuanAragao Why did you merge? We had still some things to change :neutral_face:

**Comment by osanyin** [comment]
@dmitryrck What changes you are thinking to do?

**Comment by dmitryrck** [comment]
@osanyin the file ` app/helpers/invoices_helper.rb` and _start using locale_, I thought  you will have change them :/

**Comment by dmitryrck** [comment]
But it is not a big deal :\

**Pull request merged**
