### PR TITLE
Docker improvements

### PR DESCRIPTION
**Pull request by osanyin**
- Add puma to project and run it on Procfile [production] and docker-composer [development].
- Update the Dockerfile removing unecessary dependencies; and add libxml2-utils because the crawler use the xmllint from this lib to format the xml file.
- Get the elasticsearch url from a env var.

### CODE REVIEW

**Comment by dmitryrck** [comment]
Please, remove the merge commit :P and the commits not related with the PR.

Let's make it concise :P 

Thank you :)

**Comment by osanyin** [comment]
Thanks @dmitryrck! I have cleaned up the PR.

**Comment by dmitryrck** [comment]
I was unable to run either production (dokku) and development env (docker-compose) with the same `Dockerfile`…

As far as I tested we need to make some changes, I did it in https://github.com/osanyin/peba/pull/1 , and, of course, comment it out :)

**Comment by osanyin** [comment]
@dmitryrck Your PR has been merged on my fork. Thank you! :)

**Comment by dmitryrck** [comment]
@osanyin Thank you :) Merged \o/

**Pull request merged**
